<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>MaksIT.Wvc210.Shared</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaksIT.Core" Version="1.6.8" />
    <PackageReference Include="MaksIT.Results" Version="2.0.4" />
  </ItemGroup>

</Project>
