<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.0</Version>
    <Product>MaksIT.Wvc210</Product>
    <AssemblyTitle>MaksIT.Wvc210</AssemblyTitle>
    <Authors>MaksIT</Authors>
    <Company>MaksIT</Company>
  </PropertyGroup>
</Project>
